// Code generated by protoc-gen-go. DO NOT EDIT.
// source: movie.proto

package model

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Movie struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Year                 string   `protobuf:"bytes,2,opt,name=year,proto3" json:"year,omitempty"`
	Type                 string   `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	ImdbID               string   `protobuf:"bytes,4,opt,name=imdbID,proto3" json:"imdbID,omitempty"`
	Poster               string   `protobuf:"bytes,5,opt,name=poster,proto3" json:"poster,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Movie) Reset()         { *m = Movie{} }
func (m *Movie) String() string { return proto.CompactTextString(m) }
func (*Movie) ProtoMessage()    {}
func (*Movie) Descriptor() ([]byte, []int) {
	return fileDescriptor_fde087a4194eda75, []int{0}
}

func (m *Movie) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Movie.Unmarshal(m, b)
}
func (m *Movie) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Movie.Marshal(b, m, deterministic)
}
func (m *Movie) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Movie.Merge(m, src)
}
func (m *Movie) XXX_Size() int {
	return xxx_messageInfo_Movie.Size(m)
}
func (m *Movie) XXX_DiscardUnknown() {
	xxx_messageInfo_Movie.DiscardUnknown(m)
}

var xxx_messageInfo_Movie proto.InternalMessageInfo

func (m *Movie) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Movie) GetYear() string {
	if m != nil {
		return m.Year
	}
	return ""
}

func (m *Movie) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Movie) GetImdbID() string {
	if m != nil {
		return m.ImdbID
	}
	return ""
}

func (m *Movie) GetPoster() string {
	if m != nil {
		return m.Poster
	}
	return ""
}

type Movies struct {
	List                 []*Movie `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Movies) Reset()         { *m = Movies{} }
func (m *Movies) String() string { return proto.CompactTextString(m) }
func (*Movies) ProtoMessage()    {}
func (*Movies) Descriptor() ([]byte, []int) {
	return fileDescriptor_fde087a4194eda75, []int{1}
}

func (m *Movies) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Movies.Unmarshal(m, b)
}
func (m *Movies) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Movies.Marshal(b, m, deterministic)
}
func (m *Movies) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Movies.Merge(m, src)
}
func (m *Movies) XXX_Size() int {
	return xxx_messageInfo_Movies.Size(m)
}
func (m *Movies) XXX_DiscardUnknown() {
	xxx_messageInfo_Movies.DiscardUnknown(m)
}

var xxx_messageInfo_Movies proto.InternalMessageInfo

func (m *Movies) GetList() []*Movie {
	if m != nil {
		return m.List
	}
	return nil
}

type GetMoviesParam struct {
	SearchWord           string   `protobuf:"bytes,1,opt,name=searchWord,proto3" json:"searchWord,omitempty"`
	Page                 int32    `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMoviesParam) Reset()         { *m = GetMoviesParam{} }
func (m *GetMoviesParam) String() string { return proto.CompactTextString(m) }
func (*GetMoviesParam) ProtoMessage()    {}
func (*GetMoviesParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_fde087a4194eda75, []int{2}
}

func (m *GetMoviesParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMoviesParam.Unmarshal(m, b)
}
func (m *GetMoviesParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMoviesParam.Marshal(b, m, deterministic)
}
func (m *GetMoviesParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMoviesParam.Merge(m, src)
}
func (m *GetMoviesParam) XXX_Size() int {
	return xxx_messageInfo_GetMoviesParam.Size(m)
}
func (m *GetMoviesParam) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMoviesParam.DiscardUnknown(m)
}

var xxx_messageInfo_GetMoviesParam proto.InternalMessageInfo

func (m *GetMoviesParam) GetSearchWord() string {
	if m != nil {
		return m.SearchWord
	}
	return ""
}

func (m *GetMoviesParam) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func init() {
	proto.RegisterType((*Movie)(nil), "model.Movie")
	proto.RegisterType((*Movies)(nil), "model.Movies")
	proto.RegisterType((*GetMoviesParam)(nil), "model.GetMoviesParam")
}

func init() {
	proto.RegisterFile("movie.proto", fileDescriptor_fde087a4194eda75)
}

var fileDescriptor_fde087a4194eda75 = []byte{
	// 230 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xc1, 0x4a, 0x03, 0x31,
	0x10, 0x86, 0x5d, 0xbb, 0x59, 0xe8, 0xb4, 0x7a, 0x18, 0x54, 0x82, 0x07, 0x59, 0x72, 0x2a, 0x1e,
	0xf6, 0xd0, 0x3e, 0x82, 0x05, 0xf1, 0x20, 0xc8, 0x7a, 0xf0, 0x9c, 0x76, 0x07, 0x0d, 0x6c, 0x48,
	0x48, 0x62, 0xa1, 0x6f, 0x2f, 0x99, 0x2c, 0xb2, 0xbd, 0xcd, 0xff, 0x4d, 0x98, 0xff, 0x23, 0xb0,
	0xb2, 0xee, 0x64, 0xa8, 0xf3, 0xc1, 0x25, 0x87, 0xc2, 0xba, 0x81, 0x46, 0xf5, 0x0b, 0xe2, 0x3d,
	0x53, 0xbc, 0x03, 0x91, 0x4c, 0x1a, 0x49, 0x56, 0x6d, 0xb5, 0x59, 0xf6, 0x25, 0x20, 0x42, 0x7d,
	0x26, 0x1d, 0xe4, 0x35, 0x43, 0x9e, 0x33, 0x4b, 0x67, 0x4f, 0x72, 0x51, 0x58, 0x9e, 0xf1, 0x01,
	0x1a, 0x63, 0x87, 0xc3, 0xdb, 0x5e, 0xd6, 0x4c, 0xa7, 0x94, 0xb9, 0x77, 0x31, 0x51, 0x90, 0xa2,
	0xf0, 0x92, 0xd4, 0x33, 0x34, 0x5c, 0x1b, 0xb1, 0x85, 0x7a, 0x34, 0x31, 0xc9, 0xaa, 0x5d, 0x6c,
	0x56, 0xdb, 0x75, 0xc7, 0x5a, 0x1d, 0x2f, 0x7b, 0xde, 0xa8, 0x3d, 0xdc, 0xbe, 0x52, 0x2a, 0xcf,
	0x3f, 0x74, 0xd0, 0x16, 0x9f, 0x00, 0x22, 0xe9, 0x70, 0xfc, 0xf9, 0x72, 0x61, 0x98, 0x84, 0x67,
	0x24, 0x1b, 0x7a, 0xfd, 0x4d, 0x6c, 0x2d, 0x7a, 0x9e, 0xb7, 0x2f, 0xb0, 0xe6, 0x13, 0x9f, 0x14,
	0x4e, 0xe6, 0x48, 0xb8, 0x83, 0xe5, 0xff, 0x55, 0xbc, 0x9f, 0x6a, 0x2f, 0x7b, 0x1e, 0x6f, 0xe6,
	0x36, 0x51, 0x5d, 0x1d, 0x1a, 0xfe, 0xbb, 0xdd, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x2e, 0xea,
	0xe0, 0x8a, 0x4a, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// MovieServiceClient is the client API for MovieService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MovieServiceClient interface {
	GetMovies(ctx context.Context, in *GetMoviesParam, opts ...grpc.CallOption) (*Movies, error)
}

type movieServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMovieServiceClient(cc grpc.ClientConnInterface) MovieServiceClient {
	return &movieServiceClient{cc}
}

func (c *movieServiceClient) GetMovies(ctx context.Context, in *GetMoviesParam, opts ...grpc.CallOption) (*Movies, error) {
	out := new(Movies)
	err := c.cc.Invoke(ctx, "/model.MovieService/GetMovies", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MovieServiceServer is the server API for MovieService service.
type MovieServiceServer interface {
	GetMovies(context.Context, *GetMoviesParam) (*Movies, error)
}

// UnimplementedMovieServiceServer can be embedded to have forward compatible implementations.
type UnimplementedMovieServiceServer struct {
}

func (*UnimplementedMovieServiceServer) GetMovies(ctx context.Context, req *GetMoviesParam) (*Movies, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMovies not implemented")
}

func RegisterMovieServiceServer(s *grpc.Server, srv MovieServiceServer) {
	s.RegisterService(&_MovieService_serviceDesc, srv)
}

func _MovieService_GetMovies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMoviesParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MovieServiceServer).GetMovies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/model.MovieService/GetMovies",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MovieServiceServer).GetMovies(ctx, req.(*GetMoviesParam))
	}
	return interceptor(ctx, in, info, handler)
}

var _MovieService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "model.MovieService",
	HandlerType: (*MovieServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMovies",
			Handler:    _MovieService_GetMovies_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "movie.proto",
}
